### PR TITLE
pkg/solana: deprecate and remove legacy config

### PR DESCRIPTION
**Pull request by jmank88**
https://smartcontract-it.atlassian.net/browse/BCF-2151

For compatability, merge after:
- https://github.com/smartcontractkit/chainlink/pull/8830

### CODE REVIEW

**Review by aalu1418 — APPROVED** [review]
looks good to me! my only question is if the CI failing to build the test image is a concern? (looks like a cosmos dep)

**Comment by jmank88** [comment]
> looks good to me! my only question is if the CI failing to build the test image is a concern? (looks like a cosmos dep)

That does look odd, but we can merge the cosmos PR first to see if that helps.

**Comment by aalu1418** [comment]
> > looks good to me! my only question is if the CI failing to build the test image is a concern? (looks like a cosmos dep)
> 
> That does look odd, but we can merge the cosmos PR first to see if that helps.

I'll let @archseer or @cfal handle the cosmos side since that's what they've been working on

**Comment by cfal** [comment]
> > > looks good to me! my only question is if the CI failing to build the test image is a concern? (looks like a cosmos dep)
> > 
> > 
> > That does look odd, but we can merge the cosmos PR first to see if that helps.
> 
> I'll let @archseer or @cfal handle the cosmos side since that's what they've been working on

the `go get chainlink-solana` part of the build-image action from the CL repo somehow causes chainlink-cosmos to get removed/downgraded from the deps:

```
go: removed github.com/smartcontractkit/chainlink-cosmos v0.1.4-0.20230320152049-e4098cfa14f5
go: upgraded github.com/smartcontractkit/chainlink-solana v1.0.3-0.20230320130046-4d37840c6c1b => v1.0.3-0.20230324155609-0e07a6fe9f59
```

i saw the same behavior when i was debugging why `go get chainlink-cosmos@..` was panicking 🤔

**Comment by aalu1418** [comment]
merging - CI fails in solana repo for now but once core is bumped, everything works together 🎉 
https://github.com/smartcontractkit/chainlink/pull/8852

**Pull request merged**
