### PR TITLE
Use OIDC for AWS role assumption

### PR DESCRIPTION
**Pull request by chainchad**
TODO:
- [ ] Ensure AWS role is updated (trust policy)
- [x] Ensure environment exists
- [x] Ensure secrets have the correct role set
- [x] Ensure build-custom workflow is updated to support this

### CODE REVIEW

**Review by tateexon — COMMENTED** [review]
Just needs https://github.com/smartcontractkit/chainlink/pull/6943 to merge so we can make sure the e2e tests still work as expected.

**Comment by chainchad** [comment]
@tateexon https://github.com/smartcontractkit/chainlink/pull/6943 is now merged 👍 

What's the best way to test this is working now?

**Comment by tateexon** [comment]
> @tateexon [smartcontractkit/chainlink#6943](https://github.com/smartcontractkit/chainlink/pull/6943) is now merged 👍
> 
> What's the best way to test this is working now?

I pushed the rerun button on the job.

**Comment by tateexon** [comment]
Is this PR still needed now that these files have been rewritten to use the newer stuff?

**Comment by chainchad** [comment]
Closing as this functionality was incorporated into the new composite action.

**Pull request closed without merging**
