### PR TITLE
bump libocr; use StandardOnchainConfigCodec

### PR DESCRIPTION
**Pull request by jmank88**
Requires:
- [x] https://github.com/smartcontractkit/chainlink-relay/pull/68

### CODE REVIEW

**Review by vyzaldysanchez — DISMISSED** [review]

**Review by aalu1418 — COMMENTED** [review]
just needs a `go mod tidy` in the `tests` folder

**Review by aalu1418 — APPROVED** [review]

**Comment by reductionista** [comment]
Took a look at this very odd but consistent smoke test failure:
```
E0816 00:23:37.563659   10251 portforward.go:406] an error occurred forwarding 46141 -> 6688: error forwarding port 6688 to pod 12bbd24d683d2332c05861b81d56c8d90128225b86e83a778ebe9250ceb44e42, uid : exit status 1: 2022/08/16 00:23:37 socat[22702] E connect(5, AF=2 127.0.0.1:6688, 16): Connection refused
E0816 00:23:37.563837   10251 portforward.go:234] lost connection to pod
12:23AM WRN Found no CSA Keys on the node Node URL=http://localhost:46141
STEP: Tearing down the environment 08/16/22 00:23:37.564

------------------------------
• [FAILED] [284.280 seconds]
Solana OCRv2 [BeforeEach]
/home/runner/work/chainlink-solana/chainlink-solana/tests/e2e/smoke/ocr2_test.go:16
  with Solana
  /home/runner/work/chainlink-solana/chainlink-solana/tests/e2e/smoke/ocr2_test.go:22
    performs OCR round
    /home/runner/work/chainlink-solana/chainlink-solana/tests/e2e/smoke/ocr2_test.go:23

  Begin Captured GinkgoWriter Output >>
    STEP: Deploying OCRv2 cluster 08/16/22 00:19:00.698
    STEP: Tearing down the environment 08/16/22 00:23:37.564
  << End Captured GinkgoWriter Output

  Unexpected error:
      <*url.Error | 0xc0008942a0>: {
          Op: "Get",
          URL: "http://localhost:46141/v2/keys/csa",
          Err: <*errors.errorString | 0xc000070110>{s: "EOF"},
      }
      Get "http://localhost:46141/v2/keys/csa": EOF
  occurred
  In [BeforeEach] at: /home/runner/work/chainlink-solana/chainlink-solana/tests/e2e/common/test_common.go:311

  Full Stack Trace
    github.com/smartcontractkit/chainlink-solana/tests/e2e/common.(*OCRv2TestState).SetAllAdapterResponsesToTheSameValue(0xc00042c8c0, 0x24b70c0?)
        /home/runner/work/chainlink-solana/chainlink-solana/tests/e2e/common/test_common.go:311 +0x179
    github.com/smartcontractkit/chainlink-solana/tests/e2e/smoke.glob..func1.1.1()
        /home/runner/work/chainlink-solana/chainlink-solana/tests/e2e/smoke/ocr2_test.go:19 +0x46
    github.com/smartcontractkit/chainlink-solana/tests/e2e/smoke.glob..func1.1()
        /home/runner/work/chainlink-solana/chainlink-solana/tests/e2e/smoke/ocr2_test.go:17 +0x65
```
It passes when launched with `make test_smoke` locally, but fails when launched through github CI

In CI, it successfully calls `node.ReadCSAKeys()` for each of the 5 chainlink nodes inside `node.CreateBridge()` during job creation, but then fails as soon as `node.ReadCSAKeys()` is called for the second time on the first chainlink node, inside `state.SetAllAdapterResponsesToTheSameValue(10)`.

The port forwarding is failing--possibly due to trying to forward it twice to the same port?

**Comment by jmank88** [comment]
Manually triggered with corresponding core change here:
https://github.com/smartcontractkit/chainlink-solana/actions/runs/2912760737
Screenshot from 2022-08-23 10-25-42
:heavy_check_mark: greenzo!

**Comment by aalu1418** [comment]
chicken / egg scenario with breaking change in libocr, pointing smoke test to corresponding core branch ✅ 
https://github.com/smartcontractkit/chainlink-solana/runs/7977242906?check_suite_focus=true

e2e tests against core `develop` will continue to fail until https://github.com/smartcontractkit/chainlink/pull/7087 is merged

using admin override to merge PR without all required checks passing

**Pull request merged**
