### PR TITLE
pkg/solana:  bump relay to v0.1.2; remove evmutil/geth dependency

### PR DESCRIPTION
**Pull request by jmank88**
By in-lining the body of one helper func from `package evmutil`, we can avoid the `go-ethereum` import and reduce the total number of modules dramatically:
```diff
$ go list -m all | wc -l
-467
+353
```
- [ ] Requires https://github.com/smartcontractkit/chainlink-relay/pull/60

### CODE REVIEW

**Review by aalu1418 — COMMENTED** [review]
I wonder if this would be better in the relay repo? i think it's reusable across multiple integrations?

**Review by aalu1418 — DISMISSED** [review]
might need to update the relay version in the e2e tests + go mod tidy for the CI?

**Comment by jmank88** [comment]
> might need to update the relay version in the e2e tests + go mod tidy for the CI?

Yeah this one is still a little wonky with the relative import and btcsuite issue...but trying to update now..

**Comment by jmank88** [comment]
@aalu1418 Greenzo :green_circle:

**Review by topliceanu — APPROVED** [review]

**Pull request merged**
