### PR TITLE
Fix fund command to work with ledger

### PR DESCRIPTION
**Pull request by RodrigoAD**

### CODE REVIEW

**Review by aalu1418 — DISMISSED** [review]
lgtm! (and was tested)

**Review by archseer — DISMISSED** [review]

**Review by aalu1418 — APPROVED** [review]

**Comment by RodrigoAD** [comment]
@aalu1418 @archseer The CI is failing, don't know why, could you take a look?

**Comment by archseer** [comment]
It's failing on all branches since the e2e setup got redone, feel free to ignore that

**Comment by aalu1418** [comment]
> It's failing on all branches since the e2e setup got redone, feel free to ignore that

I think it's fixed now with https://github.com/smartcontractkit/chainlink-solana/pull/434 - but yeah the failure is ok in this case since it's unrelated code

**Pull request merged**
